version: '2'
services:
    dbtheory-app:
        image: dbtheory
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dbtheory-postgresql:5432/dbtheory
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dbtheory-postgresql:
        extends:
            file: postgresql.yml
            service: dbtheory-postgresql
